# MUSUBI Project Configuration
name: MS-GraphRAG+LazyGraphRAG
description: LazyGraphRAGクエリアルゴリズムの完全実装プロジェクト
locale: ja
version: "1.0.0"
created: 2025-12-22
updated: 2025-12-24

# Repository
repository: https://github.com/nahisaho/altanative-lazygraphrag
documentation:
  qiita: https://qiita.com/hisaho/items/bfe37d70c291380f8d67
  readme: README-LazyGraphRAG.md

# Technology Stack
tech_stack:
  approach: existing-codebase-extension
  languages:
    - python  # 3.10+
  frameworks:
    - graphrag  # Microsoft GraphRAG
  key_libraries:
    - pandas
    - networkx
    - tiktoken
    - textblob
    - pydantic

# Current Phase
phase: implementation-complete
features:
  - id: lazy-search
    name: LazyGraphRAG Query Algorithms
    status: implemented
    specs:
      - storage/specs/REQ-LAZY-001-query-algorithms.md
      - storage/specs/SPEC-LAZY-001-query-algorithms.md
    implementation:
      - graphrag/query/structured_search/lazy_search/
      - graphrag/config/models/lazy_search_config.py
    tests:
      unit: 45
      integration: 23
      total: 68
    benchmarks:
      max_chunks: 1000000
      max_queries: 1000
      avg_time_per_query: 3.1s
